# .readthedocs.yaml
# Read the Docs configuration file
# For details: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# Build settings
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

# Python dependencies
python:
  install:
    - requirements: requirements.txt  # Reference the root-level requirements.txt
    - method: setuptools  # Install your package (if applicable)

# Sphinx configuration
sphinx:
  configuration: docs/conf.py  # Path to your Sphinx configuration file

